### ISSUE TITLE
Google Tag Manager integration relies on global window.analytics

### ISSUE THREAD

**Issue by antgonzales** [segmentio/analytics-next#534] opened 2022-07-12 22:27 UTC
Hello 👋 I'm attempting to use the browser version of analytics-next as detailed in the [docs](https://github.com/segmentio/analytics-next#using-react-advanced-w-react-context). However, it doesn't appear to work well with the Google Tag Manager integration. When I attach the analytics instance to the `window` object like `window.analytics = analytics` in the `useEffect()` hook, the error goes away. Do we need to attach analytics to the window for integrations to work?

I believe these are the lines causing the error:
https://github.com/segmentio/analytics.js-integrations/blob/master/integrations/google-tag-manager/lib/index.js#L98-L99

**Comment by chrisradek** [comment] 2022-07-13 20:22
@antgonzales Thanks for reporting this issue! You should not need to set `window.analytics` for the integration to work - `analytics` will set itself on the integration while loading the integration.

I tried reproducing the issue you're seeing in a simple app without react but haven't had luck yet. Can you share a minimal repro that causes this issue? Also, can you share what version of analytics-next you're using?

**Comment by chrisradek** [comment] 2022-07-14 21:27
@antgonzales I created a sample repo based on the readme and create-react-app here but wasn't able to reproduce the issue you're seeing:
https://github.com/chrisradek/ajs-next-534

You can try it out as well by replacing the writeKey to match your source:
https://github.com/chrisradek/ajs-next-534/blob/28f8c74c22894706305b778dcecba56fa63a922a/src/App.js#L7

I ran this with a source using GTM and was able to load the gtm bundle (the `Test` text on the website is coming from GTM):
<img width="1706" alt="segment-gtm-sample" src="https://user-images.githubusercontent.com/14189820/179088686-1a42d983-3b96-4b0d-a65d-d5da0822e79a.png">

In my example I'm using `@segment/analytics-next` version `1.40.0`. Can you try out that repo with your writeKey and see if you still see this issue?

**Comment by antgonzales** [comment] 2022-07-26 18:04
@chrisradek hey there, I recently forked the repo you created here https://github.com/antgonzales/ajs-next-534. I added my company's Segment write key to the example and started the application with the same problem persisting that occurs on my company's website. Is there maybe a way to control versions of GTM through Segment?

Please see the screenshots attached to let me know if you need anything else:

![Image 2022-07-26 at 1 59 45 PM](https://user-images.githubusercontent.com/3740655/181078968-dafaaf0a-01fd-446e-9ee5-4dddb5f6ad2e.jpg)

![ajs-next-534 node --version   nvim   2022-07-26 at 1 56 28 PM](https://user-images.githubusercontent.com/3740655/181079092-b57563ec-c9b7-4f01-b7eb-3e2bd16eb1ce.jpg)

**Comment by chrisradek** [comment] 2022-07-26 20:29
@antgonzales Wow, that's really interesting! 

> Is there maybe a way to control versions of GTM through Segment?

I'm not super familiar with GTM - we'll just load it from their endpoint. You can specify the containerId and the environment properties which become part of the URL to fetch GTM but I'm not aware if GTM supports any other versionining on their end.

I've tried the repo with a few other writeKeys and haven't gotten the same error to appear yet. Is this happening on a public site that you can share? If you open up a ticket with support I'd be happy to look into why your source seems to be having issues loading GTM as well.

**Comment by chrisradek** [comment] 2022-08-02 16:17
Closing since this was resolved via support.

**Closed by chrisradek** 2022-08-02 16:17 UTC

**Comment by antgonzales** [comment] 2022-08-04 14:56
For reference, in case anyone is curious or finds this issue. I believe the culprit is the team managing our Google Tag Manager includes a script that attempts to call `window.analytics`. Because we're removing the attachment to the window, the error popped up. Thanks @chrisradek for helping me solve this problem!
