### ISSUE TITLE
[Compilation Issue] Type error: Unused '@ts-expect-error' directive.

### ISSUE THREAD

**Issue by yordis** [segmentio/analytics-next#311] opened 2021-10-31 06:34 UTC
Using `NextJS` default configuration, we are getting the following issue:

```text
02:13:30.821 | ./node_modules/@segment/analytics-next/src/analytics.ts:460:9
-- | --
02:13:30.821 | Type error: Unused '@ts-expect-error' directive.

```

![Screen Shot 2021-10-31 at 2 32 46 AM](https://user-images.githubusercontent.com/4237280/139571179-b61c74b3-d9be-4a94-8f3c-bebea77928d4.png)

**Comment by pooyaj** [comment] 2021-11-01 16:44
@yordis having a hard time reproducing this on a fresh Next.JS Typescript project. Any idea what could be different between default NextJS `tsconfig.json` and your project's? Could be a typescript version as well, could you please check your TS version?

**Comment by yordis** [comment] 2021-11-01 22:31
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "strict": false,
    "noImplicitAny": false,
    "incremental": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "include": [
    "src"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

that is what we have at the moment.

**Comment by pooyaj** [comment] 2021-11-02 23:55
Unfortunately still cannot reproduce using the above config in my NextJS app, but in your App the library is somehow getting Typechecked using your own tsconfig.json ( which has `"strict": false` and that is causing the error ) ... but the strange part is that the `node_modules` is excluded in tsconfig, and `skipLibCheck` is set to true.

**Comment by yordis** [comment] 2021-11-04 13:17
```json
{ "next": "11.1.2" }
```

Yeah, I am not sure what is going on honestly, the issue persists

**Comment by digitalbase** [comment] 2021-12-29 10:58
Same issue.

Typescript 4.5.2,  NextJs 12.0.7

**Comment by digitalbase** [comment] 2021-12-29 11:30
Stupid me. I was importing incorrectly:

```
import { Context } from '@segment/analytics-next/src/core/context';
import type { Plugin } from '@segment/analytics-next/src/core/plugin';
```

Changing it to 

```
import { Context } from '@segment/analytics-next';
import type { Plugin } from '@segment/analytics-next';
```

I found out by use tsc --listFiles and noticed that typescript was checking files that should not be checked (excluded in tsconfig).

**Comment by pooyaj** [comment] 2021-12-29 18:33
Awesome, thanks for the guidance! Probably similar issue with the other report of this error. So I'm going to close this issue.

**Closed by pooyaj** 2021-12-29 18:33 UTC

**Comment by yordis** [comment] 2022-01-06 18:13
@digitalbase you are amazing, that was the actual issue.

@pooyaj which is leading me to deal with some issues because some types are not being exported from the root.

I am working in some React abstraction https://github.com/segmentio/analytics-next/issues/310 that is leading me to care about this internals thou.
