### ISSUE TITLE
@segment/analytics-node - Release Version 1.0

### ISSUE THREAD

**Issue by Jackman3005** [segmentio/analytics-next#732] opened 2022-12-20 07:56 UTC
Hi!

I'm trying to find a way to be notified of when the [@segment/analytics-node](https://github.com/segmentio/analytics-next/tree/master/packages/node) library is ready to come out of beta.

Maybe this issue can be a good location to keep track of what is remaining to get a 1.0 release out. That way *anyone else who wants to use the library once it is out of beta can also subscribe to this issue* and be ready to try it out when it gets closed.

If anyone has a better way to subscribe to just @segment/analytics-node releases I'm happy to do that instead.

Cheers,
Jack

**Comment by silesky** [comment] 2022-12-20 20:30
Thanks @Jackman3005 for posting this. I appreciate the feedback and any feedback in general about this beta will be tremendously helpful; we've done testing in various sandboxes as well as running durability and performance tests, but any feedback from running it in production is really appreciated.

I can post here whenever we release a new version. Our next release will be after the holidays, which is mostly refactoring and some improvements to our typescript interfaces.

To answer about the timeline: our official "non-beta" release is scheduled for the end of Q1, but the API should be stable as of this message (beyond some typescript tweaks). We use the term "beta" at Segment, but this phase is actually meant to be more of a release candidate -- meaning, that if this library was used internally, we would feel good using it in our own production environment.

**Comment by silesky** [comment] 2023-01-04 22:19
Released beta-9, which includes housecleaning and Typescript improvements.

**Comment by silesky** [comment] 2023-01-10 04:17
Released beta.12, which fixed more issues around  Cloudflare workers / web workers.

**Comment by silesky** [comment] 2023-01-31 16:42
0.0.1-beta.17 released.

**Comment by viniciuspalma** [comment] 2023-02-22 12:16
Hi @silesky, that last version `0.0.1-beta.17` has a missing dependency the problem is imported from @segment/analytics-core@1.1.1

The issue was fixed in this [commit](https://github.com/segmentio/analytics-next/commit/98d1b127082f5fc7904980a561220c64c26edff3#diff-03c79f5260456dae9c6e77d46e2f0dac0d91d76277dd5fd247f97bf0e9610776L12) since the dependency that was not included in the package.json was removed

But how the current published version of the node library is relaying in an old version of core the issue appears on more strict package managers as yarn PnP

Can we be waiting for the version 0.0.1 soon to be published?

**Comment by eugenerr** [comment] 2023-02-23 02:19
I've been following README with
- in my package.json `"@segment/analytics-node": "^0.0.1-beta.17"`
- importing as `import { Analytics } from '@segment/analytics-node';`
- this is express application, `npm start`, fails with
```
SyntaxError: Named export 'Analytics' not found. The requested module '@segment/analytics-node' is a CommonJS module, which may not support all module.exports as named exports.
```
- node version 16.14.2
- looking in @segment's own package.json, no `"type": "module"` there, it's a CommonJS indeed but syntax is ESM

@silesky could you advice?

**Comment by silesky** [comment] 2023-02-23 02:30
> Hi @silesky, that last version `0.0.1-beta.17` has a missing dependency the problem is imported from @segment/analytics-core@1.1.1
> 
> The issue was fixed in this [commit](https://github.com/segmentio/analytics-next/commit/98d1b127082f5fc7904980a561220c64c26edff3#diff-03c79f5260456dae9c6e77d46e2f0dac0d91d76277dd5fd247f97bf0e9610776L12) since the dependency that was not included in the package.json was removed
> 
> But how the current published version of the node library is relaying in an old version of core the issue appears on more strict package managers as yarn PnP
> 


Hey @viniciuspalma, The current published version of the node [library uses 1.2.1](https://www.npmjs.com/package/@segment/analytics-node?activeTab=explore)-- I would advise trying to solve it on your end.

**Comment by silesky** [comment] 2023-02-23 02:38
> I've been following README with
> 
> * in my package.json `"@segment/analytics-node": "^0.0.1-beta.17"`
> * importing as `import { Analytics } from '@segment/analytics-node';`
> * this is express application, `npm start`, fails with
> 
> ```
> SyntaxError: Named export 'Analytics' not found. The requested module '@segment/analytics-node' is a CommonJS module, which may not support all module.exports as named exports.
> ```
> 
>  * node version 16.14.2
> * looking in @segment's own package.json, no `"type": "module"` there, it's a CommonJS indeed but syntax is ESM
> 
> @silesky could you advice?

Hey, I'm not by my computer RN, but does default import work i.e can you do "import Analytics from '@segment/analytics-node'"?

**Comment by silesky** [comment] 2023-02-23 22:28
@viniciuspalma I think you want to do:
`yarn up --exact @segment/analytics-node`. Even though the beta versions are marked as "latest", the bad rc version still seems to install.

**Comment by eugenerr** [comment] 2023-02-23 23:02
Hi @silesky I'd like to use single package manager in build script, i.e. no yarn, `npm install` only.
Trying in package.json without semversion `"@segment/analytics-node": "1.0.0-beta.19"`, No matching version found for @segment/analytics-node@1.0.0-beta.19.
For your question regarding default import, it didn't work either but going with just `"analytics-node": "^6.2.0"` installs and I could import, default one only.
Not sure package above is in working state. No error in analytics.track but no events flowing seen in Segment debugger. Could be unrelated issue of course.

**Comment by eugenerr** [comment] 2023-02-23 23:05
Hm where did I get the 19 from? Trying 0.0.1-beta.18

**Comment by silesky** [comment] 2023-02-23 23:16
> For your question regarding default import, it didn't work either but going with just "analytics-node": "^6.2.0" installs and I could import, default one only.
`analytics-node` is the old-soon-to-be-deprecated version of analytics. I'm not sure what's going on in your system, but analytics-node is definitely available. 


<img width="465" alt="image" src="https://user-images.githubusercontent.com/5115498/221052814-a1275dbf-46e5-47a4-a03e-e14e9f439e2e.png">

**Comment by eugenerr** [comment] 2023-02-23 23:27
My .npmrc pointing at company's artifactory where it's not yet published?

**Comment by eugenerr** [comment] 2023-02-26 17:01
Hi @silesky finally "@segment/analytics-node": "^1.0.0-beta.19" is in our artifactory and I have it installed. It doesn't resolve importing issue
`import Analytics from '@segment/analytics-node';`
```
(node:39714) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/eugener/Development/chatbot-logger/node_modules/@segment/analytics-node/dist/esm/index.js:1
export { Analytics } from './app/analytics-node';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
```

`import { Analytics } from '@segment/analytics-node';`
```
import { Analytics } from '@segment/analytics-node';
         ^^^^^^^^^
SyntaxError: Named export 'Analytics' not found. The requested module '@segment/analytics-node' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@segment/analytics-node';
const { Analytics } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
```

**Comment by silesky** [comment] 2023-02-26 21:39
@eugenerr, I think I found your issue. Proper support for node exports maps should be fixed in `1.0.0-beta.20`, please try it out. (https://github.com/segmentio/analytics-next/pull/807/files)

**Comment by eugenerr** [comment] 2023-02-27 14:27
@silesky thank you, confirming, importing issue has been fixed.

**Comment by silesky** [comment] 2023-04-04 17:59
beta.25 has been released, which adds a `disable` option (for tests).

**Comment by silesky** [comment] 2023-11-04 16:54
Closing since 1.x has been released.

**Closed by silesky** 2023-11-04 16:54 UTC

**Comment by Jackman3005** [comment] 2023-11-09 03:16
Awesome @silesky I hope to make the upgrade soon!
