### ISSUE TITLE
Localstorage persisted-queue not being utilized even when retry flag is set (when batching?)

### ISSUE THREAD

**Issue by mlstubblefield** [segmentio/analytics-next#361] opened 2022-01-11 21:24 UTC
We have an issue on our site where when clicking a link that also sends an event, we're not seeing those events in segment.
My answer to that was "segment uses local storage to make sure events can be sent".
However, I dove a little deeper and wasn't able to verify that this is working (at least for us).

I cracked open some of the segment-next (v2) source code, and I believe that the localstorage should be populated with keys that start with "persisted-queue".
![image](https://user-images.githubusercontent.com/7562533/149023462-6c753cde-4e00-4630-9540-9166249721d1.png)

I checked our localstorage and I'm not seeing any keys going in/out of local storage to that effect. I've also opened up the PersistedPriorityQueue class in my browser and can't get any break points to stop there. I found some suspicious code in analytics.ts
![image](https://user-images.githubusercontent.com/7562533/149023640-3388d2f7-84c7-442f-b017-1a82c557359e.png)
It looked to me that dispatchSingle didn't use any queuing, which would cause it to skip the persistence.
That being said, I also overrode `analytics.queue.isEmpty = () => false`  like so, and even calling dispatch isn't triggering breakpoints for me.

Both retries and analytics 2.0 are enabled for me.
![image](https://user-images.githubusercontent.com/7562533/149023768-e3b6f1ab-1e5d-433c-941c-faec1275d4dc.png)

**Comment by mlstubblefield** [comment] 2022-01-11 21:30
My colleague just pointed out that we're using batching and perhaps this could only be impacting folks that utilize batching.

**Comment by zikaari** [comment] 2022-01-31 22:46
Hey @mlstubblefield, can you confirm the following: 

- Is your app an SPA?
- Are those links internal or external (if external do they open in a new tab)?
- Were you _(or your customers)_ connected to the internet during the entirety of the observation?

**Comment by mlstubblefield** [comment] 2022-02-04 23:33
- Not for these links (sometimes our app is a SPA)
- Internal
- Connected to the internet
- I didn't see the persistence working in edge or chrome

Personally, after reading through the source code/doing some debugging, I'm reasonably confident that the problem is that (at least when batching is enabled), the persisted queue is not being written to always. 
Please see my technical write up from above...
![image](https://user-images.githubusercontent.com/7562533/152616470-85fc6d91-2ba8-4322-88bc-bf8f4436f96c.png)

One point on the browsers-- if that's directed towards the onbeforeunload browser event, I don't think it's that-- the data isn't making it into local storage from what I could tell. Any of the browsers that we didn't see it working with do support onbeforeunload. All of the browsers also support local storage.
What I'm saying is that dispatch single (below) doesn't even write to the persisted queue (as far as I could tell).
![image](https://user-images.githubusercontent.com/7562533/152616698-531800af-62e7-4400-8bdf-a431fca6f306.png)

Here, dispatch writes to the queue...
![image](https://user-images.githubusercontent.com/7562533/152616792-a3cef7e1-bc96-4747-bf36-3b32c8b3185a.png)

Dispatch single does not (directly at least)
![image](https://user-images.githubusercontent.com/7562533/152616816-320b1f74-a28c-4b15-a2bf-89899472cd61.png)

Note that delivery (the only "main method" that dispatch calls) also does not interact with the queue.
![image](https://user-images.githubusercontent.com/7562533/152616892-3a7370f7-f61f-484f-8022-7846888990c2.png)

**Comment by zikaari** [comment] 2022-02-08 00:24
@mlstubblefield The problem has been isolated 🎉

Batched strategy by design never had any interest in persisting the events to local storage at all. The design is to have them delivered when navigating away from the current page. This is done using the `keepalive` option on the Fetch API. The problem was the `beforeunload` event handler that flushes the batch was being called *before* the method that pushes the event to the queue when you call `analytics.track(...)`. So as far as the `beforeunload` handler was concerned the batch was empty, concluding to "no action necessary".

This has now been addressed and patch should be incoming soon.

**Comment by mlstubblefield** [comment] 2022-02-08 17:03
Excellent news! And If I recall, I shouldn't have to update an NPM package or anything like that to receive this fix?

**Comment by zikaari** [comment] 2022-02-09 00:55
You won't need to do anything when the patch is deployed _(I will let you know when it goes live)_.

Before we deploy, please test the patch locally on your machine by pointing to this build of `https://cdn.se.../analytics.min.js` - https://cdn.segment.com/analytics-next/br/fix-batched-dispatcher/latest/standalone.js

**Comment by zikaari** [comment] 2022-02-15 21:51
@mlstubblefield Please try out the patch on your local machine by following the instructions in the comment above.

**Comment by jawach1** [comment] 2022-02-28 03:50
@zikaari @mlstubblefield I had a chance to test this out and it seems to be working great! The event "PDP - Summary - Recommendations" was the one that was getting lose before as it gets fired on a <a> link to a new page that reloads segment. With the new js you provided it seems to be able to sneak out a new batch just before the page switches. When will this be deployed the live live Segment script? Thanks for your help!
![image](https://user-images.githubusercontent.com/67655294/155920981-a57d7a89-cfd5-42a6-a59f-6c9bc58c1308.png)

**Comment by zikaari** [comment] 2022-03-01 00:10
@pooyaj its ready to go!

**Comment by pooyaj** [comment] 2022-03-23 05:04
Fixed in v1.34.0 💥

**Closed by pooyaj** 2022-03-23 05:04 UTC
