### ISSUE TITLE
Allow cdn in AnalyticsSettings 

### ISSUE THREAD

**Issue by chambo-e** [segmentio/analytics-next#362] opened 2022-01-12 14:47 UTC
Hello 👋 

If I understand correctly the current way to set the cdn is this 

```ts
window.analytics._cdn = <cdn>
```

Because this variable can then be reused in the plugins 

We try to avoid touching the window object as much as possible 
Would it be possible to pass the cdn in the AnalyticsSettings which is then passed down to the plugins ? 

```ts
AnalyticsBrowser.load({ writeKey, cdn })
```

```ts
export function loadLegacySettings(writeKey: string, cdn: string): Promise<LegacySettings> {
  return fetch(`${cdn}/v1/projects/${writeKey}/settings`)
    .then((res) => ({ ...res.json(), cdn }))
    .catch((err) => {
      console.warn('Failed to load settings', err)
      throw err
    })
}
```

Thanks :)

**Comment by pooyaj** [comment] 2022-01-12 17:24
Hi @chambo-e, good suggestion. We are planning to improve the configurability of the library for `npm` users. Took a note of the `_cdn` variable as well to be included in the scope. This won't land immediately, but we are pushing to ship this quarter.

**Comment by chambo-e** [comment] 2022-02-02 12:01
Thanks :)

By any chance do you have a public roadmap which would allow us to close this issue ?

**Comment by yordis** [comment] 2022-03-23 04:05
Any updates on this one?

**Comment by pooyaj** [comment] 2022-03-23 05:02
Thanks for checking! We just released this feature in 1.34.0. 
More info: 
PR: https://github.com/segmentio/analytics-next/pull/389
Release: https://github.com/segmentio/analytics-next/releases/tag/v1.34.0

**Comment by yordis** [comment] 2022-03-23 16:58
@pooyaj I am a bit confused because I do want to hit the CDN to retrieve such information just that we need to use our Proxy Server to bypass problems with Ad Blockers and whatnot.

**Comment by pooyaj** [comment] 2022-03-23 22:18
@yordis my bad closing this, as passing hardcoded settings won't solve this particular issue. I think we still need to implement passing custom CDN endpoint for proxy users 😅 hopefully coming up soon!

**Comment by yordis** [comment] 2022-03-24 03:58
@pooyaj I created a PR for it, let me know if that works

**Closed** 2022-04-06 02:41 UTC

**Comment by vicpara** [comment] 2022-04-07 19:11
I am using the v1.35.0 of `@analytics-next` that includes this fix. I can see on the network how how `settings` is retrieved from the custom domain cdn via the `cdnURL` property.

On the other hand, we are using segment with another 3rd party provider (eg. MouseFlow ). Even though the CDN is correctly configured I can see on the network how other 3rd party resources are still retrieved from segment CDN instead of using the customer proxy url.
Do you have any further guidance on how to force the integrations to rely on the custom proxy cdn ?

Thanks

**Comment by silesky** [comment] 2022-04-07 20:00
> I am using the v1.35.0 of `@analytics-next` that includes this fix. I can see on the network how `settings` is retrieved from the custom domain cdn via the `cdnURL` property.
> 
> On the other hand, we are using Segment with other 3rd party providers (eg. MouseFlow ). Even though the CDN is correctly configured I can see on the network how other 3rd party resources are still retrieved from segment CDN instead of using the customer proxy url. (eg. https://cdn.segment.com/next-integrations/integrations/mouseflow/2.2.3/mouseflow.dynamic.js.gz )
> 
> Do you have any further guidance on how to force the integrations to rely on the custom proxy cdn ?
> 
> Thanks

Thanks for bringing this to my attention, I'm looking into this. In the meantime, you can still do something like this (assuming you're using react):
```ts
const useAnalytics = (writeKey: string, staging = true) => {
  const [analytics, setAnalytics] = React.useState<Analytics | undefined>(
    undefined
  );
  useEffect(() => {
    const loadAnalytics = async () => {
          (globalThis as any).analytics = {
            _cdn: "https://cdn.segment.build",
          };
        let [response, ctx] = await AnalyticsBrowser.load({
          writeKey,
        });
  ....
    };
    loadAnalytics();
  }, [writeKey]);
  if (analytics) {
    return new MyAnalytics(analytics);
  }
  return undefined;
};
```

**Comment by vicpara** [comment] 2022-04-07 20:14
I am loading `analytics-next` via npm package manager and I set the cdn in the .load method like shown below. This works well for Segment artifacts but not for the 3rd party plugins.

```javascript
    AnalyticsBrowser.load(
        {
          writeKey: '12..34',
          cdnURL: 'https://cdn.customdomain.com',
        },
        {
          integrations: {
            'Segment.io': {
              apiHost: 'api.customdomain.com/v1',
            },
          },
        }
      )
```

I checked 'https://github.com/segmentio/analytics.js-integrations/blob/master/integrations/mouseflow/lib/index.js' which shows that the actual integration has a hardcoded url. 

1. I'm not sure if this link from `analytics.js-integration` is still relevant to this particular topic.
2. Wanted to check you don't have any magic flag or setting that would rewrite the plugin source based on the CDN hostname.

**Comment by silesky** [comment] 2022-04-07 22:13
@vicpara Thanks for sleuthing; no, unfortunately I don't think we have anything to auto rewrite the src based on the CDN hostname. Maybe @pooyaj  can chime in?

**Comment by pooyaj** [comment] 2022-04-07 22:33
hey @vicpara, the expected behavior for setting `cdnURL` is that all assets that were previously being loaded from `cdn.segment.com` should now be loaded from `cdn.customdomain.com` including `mouseflow.dynamic.js.gz`. But the actual mouseflow SDK ( that is referenced in the plugin source code ) will still load from `cdn.mouseflow.com`.

**Comment by pooyaj** [comment] 2022-04-07 22:33
If you see `mouseflow.dynamic.js.gz` is being loaded from `cdn.segment.com` then we have to take a look at it

**Comment by vicpara** [comment] 2022-04-07 22:47
@pooyaj Thanks for your answer and for looking into this.

Currently I see the following assets still being downloaded from the segment cdn:
`https://cdn.segment.com/next-integrations/integrations/mouseflow/2.2.3/mouseflow.dynamic.js.gz`
`https://cdn.segment.com/next-integrations/integrations/vendor/commons.5xxxxxxe.js.gz` 

`5xxxxxxe` is an actual longer string that might be an identifier. I redacted it for this rason. If it helps I am happy to share it with you.

**Comment by pooyaj** [comment] 2022-04-07 22:50
I see! then it is a bug on our end 😅 we will look into it and hopefully should be able to release the fix

**Comment by silesky** [comment] 2022-04-08 17:50
@vicpara working on this in https://github.com/segmentio/analytics-next/pull/424
